### ISSUE TITLE
Fantastic menu. 

### ISSUE THREAD

**Issue by fullakingi** [Pagawa/PgwMenu#1]
Hi. really love your menu. I can't get the burger icon to appear on my site when it scales down to mobile and I cant seem to find the breakpoints... I tried to download the documentation to check if i had it all appearing ok...  but the link was not working and i couldn't find a demo HTML page and I couldnt easily check he js on your page because it was all put inline and minified.  I'm wondering if I have the proper version of javascript?  Or there's another conflict?

if you get a chance to give me a quick idea, I really appreciate it. BTW your page http://pgwjs.com/pgwmenu/ has an unbelieveably good score on Google Page Speed Inisghts!  nice.

GITHUB
https://github.com/IgniteStudiosLtd/one-page-flow

DEMO
http://ignitestudios.org/one-page-flow/
![screenshot 2015-04-26 13 54 18](https://cloud.githubusercontent.com/assets/6522361/7339931/c3bf87c0-ec1b-11e4-86bf-0ec77b6f5008.png)

**Comment by jonathan-piat** [comment]
Hello,

It seems that you have a 404 error on "pgwmenu.js", can you test with "js/pgwmenu.js"?

Regards

**Comment by fullakingi** [comment]
thanks so much. so sorry to bug you with this silly thing. it's working now
:)

**Comment by fullakingi** [comment]
Jonathan is awesome!
